version: "2"

services:
  builder:
    build: ./builder
    volumes:
      - "./build:/gopath/bin/"
  auth:
    build: .
    links:
      - db
    ports:
      - "8000:10000"
  db:
    image: mvertes/alpine-mongo:latest
    volumes:
      - data:/var/lib/mongodb

volumes:
  data:
    driver: local
