version: "2"

services:
  builder:
    build: ./builder
    volumes:
      - "./build:/gopath/bin/"
  auth:
    build: .
    links:
      - db
    depends_on:
      - builder
    ports:
      - "8000:8000"
  db:
    image: mvertes/alpine-mongo:latest
    volumes:
      - /data/db:/data/db