database:
  host: localhost
  dbname: testdb
  tokentable: tokentable
  usertable: usertable
router:
  register:
    path: /register
  login:
    path: /login
  validate:
    path: /validate
  logout:
    path: /logout
  update:
    path: /update
  resetpassword:
    path: /reset
domain: my.domain.com
ip: 0.0.0.0:8000